routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
Route::get('user', ['middleware' => 'auth', function () {
    return view('/welcome');
}]);

//Route::get('admin', ['middleware' => 'isadmin', function () {
  //  return view('admin');
//}]);

Route::get('welcome', function () {
    return view('welcome');
});

Route::get('about', function () {
    return view('about');
});

Route::get('help', function () {
    return view('help');
});

Route::get('help&support', function () {
    return view('help');
});

Route::get('services-special', function () {
    return view('services.special');
});

Route::get('services-advertising', function () {
    return view('services.advertising');
});

Route::get('services-baggage', function () {
    return view('services.baggage');
});

Route::get('services-careers', function () {
    return view('services.careers');
});

Route::get('help-translate', function () {
    return view('help-translate');
});

Route::get('p', function () {
    return view('payment-email');
});

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('/down', function(){
    Artisan::call('down');
});

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');



Auth::routes(['verify' => true]);

Route::resource('cities','citycontroller');

Route::resource('cities.save','citycontroller@store');
Route::resource('trains','traincontroller');
Route::resource('trips','tripcontroller');
Route::resource('passengers','passengercontroller');
Route::resource('tickets','ticketcontroller');
Route::post('/store1','citycontroller@store');
Route::put('/upd1/{id}','citycontroller@update');
Route::delete('/del1/{id}','citycontroller@destroy');
Route::resource('useres','usercontroller');
Route::post('/store3','tripcontroller@store');
Route::put('/upd3/{id}','tripcontroller@update');
Route::delete('/del3/{id}','tripcontroller@destroy');
Route::resource('myprofile','rigestercontroller');

Route::put('/upd/{id}','rigestercontroller@update');
Route::delete('/del/{id}','rigestercontroller@destroy');
Route::resource('feedback','commentcontroller');
Route::post('/store','commentcontroller@store');
Route::get('/disscount', function(){
    Mail::send('inform',[],function($m){
        $m->to('user@gmail.com')->subject('Apollon');
    });
    return view ('welcome');
});
Route::post('/search','searchcontroller@search');
Route::get('/payment','paymentController@index');
Route::post('/charge','paymentController@charge');



Route::get('/invoice', function(){
    $pdf = PDF::loadView('invoice');
    return $pdf->download('invoice.pdf');
});
Route::get('/invoices', 'paymentController@showAccount');
Route::get('/admin', function () {
    return view('admin.dashboard');
  });
  Route::get('ad', function () {
    return view('admins');
});
Route::get('ad','admincontroller@index');


Route::post('/uplade','usercontroller@updateavatar');
Route::post('/store2','traincontroller@store');
Route::put('/upd2/{id}','traincontroller@update');
Route::delete('/del2/{id}','traincontroller@destroy');

resources/views/useres/index.blade.php
@extends('layouts.app')
@section('content')
    

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ADmin Appolo</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </head>
  <body>
      <h1>Users </h1>
      <br>
      <table class="table table-bordered table-dark">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">is_Admin</th>
            <th scope="col">name</th>
            <th scope="col">email</th>
           
          </tr>
        </thead>
        <tbody>
            @foreach($useres as $i)
            <tr>
                <td>{{$i->id}}</td>
                <td>{{$i->isAdmin}}</td>
                <td>{{$i->name}}</td>
                <td>{{$i->email}}</td>
               
               
           
            </tr>
            @endforeach
        </tbody>
      </table>
     
      
      <style>
          @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500');
*{
  padding: 0;
  margin: 0;
  list-style: none;
  text-decoration: none;
}
body {
  font-family: 'Roboto', sans-serif;
  color: green;
}
.sidebar {
  position: fixed;
  left: -250px;
  width: 250px;
  height: 100%;
  background: #042331;
  transition: all .5s ease;
}
.sidebar header {
  font-size: 22px;
  color: white;
  line-height: 70px;
  text-align: center;
  background: #063146;
  user-select: none;
}
.sidebar ul a{
  display: block;
  height: 100%;
  width: 100%;
  line-height: 65px;
  font-size: 20px;
  color: white;
  padding-left: 40px;
  box-sizing: border-box;
  border-bottom: 1px solid black;
  border-top: 1px solid rgba(255,255,255,.1);
  transition: .4s;
}
ul li:hover a{
  padding-left: 50px;
}
.sidebar ul a i{
  margin-right: 16px;
}
#check{
  display: none;
}
label #btn,label #cancel{
  position: absolute;
  background: #042331;
  border-radius: 3px;
  cursor: pointer;
}
label #btn{
  left: 40px;
  top: 25px;
  font-size: 35px;
  color: white;
  padding: 6px 12px;
  transition: all .5s;
}
label #cancel{
  z-index: 1111;
  left: -195px;
  top: 17px;
  font-size: 30px;
  color: #0a5275;
  padding: 4px 9px;
  transition: all .5s ease;
}
#check:checked ~ .sidebar{
  left: 0;
}
#check:checked ~ label #btn{
  left: 250px;
  opacity: 0;
  pointer-events: none;
}
#check:checked ~ label #cancel{
  left: 195px;
}
#check:checked ~ section{
  margin-left: 250px;
}
section{
  background: url(bg.jpeg) no-repeat;
  background-position: center;
  background-size: cover;
  height: 100vh;
  transition: all .5s;
}
h2
{
    color: green;
}

      </style>
    <input type="checkbox" id="check">
    <label for="check">
      <i class="fas fa-bars" id="btn"></i>
      <i class="fas fa-times" id="cancel"></i>
    </label>
    <div class="sidebar">
       
    <header>
        <ul>
            <i class="fas fa-user-cog"></i>
           <h2>online</h2>
           <i class="fad fa-octagon"></i>
            
        </ul>
    </header>
  <ul>
    <li><a href="#"><i class="fas fa-qrcode"></i>Dashboard</a></li>
   <li ><a href="" ><i class="fas fa-user"></i>User</a></li> 
    <li><a href="#"><i class="fas fa-city"></i>cities</a></li>
    <li><a href="#"><i class="fas fa-calendar-check"></i>ticket </a></li>
    <li><a href="#"><i class="fas fa-suitcase-rolling"></i>Passenger List</a></li>
    <li><a href="#"><i class="fas fa-train"></i>Trips</a></li>
    <li><a href="#"><i class="fas fa-cogs"></i>Settings</a></li>
  </ul>
</div>
 <section></section>
 
 
  </body>
</html>
@endsection

resources/views/useres/myprofile.blade.php
@extends('layouts.app')

@section('content')

<style>
  .myprofile-main {
    background-color: var(--body-background);
  }

  .input {
    width: 24%;
  }

  .myset {
    font-size: 25px;
  }

  .edit {
    margin-right: 2%;
  }
</style>
<div class="myprofile-main">
  <div class="container myprofile pt-5 pb-5">
    <h2 class="my-set text-center">{{ __('msg.myprofile')}} </h2>
    <hr style="border-color:black;">
    <tr>
      <p>
        <b class="text-left">{{ __('msg.prof-picture')}} :</b>
        <br>
        <img src="/uploads/avatars/{{ Auth::user()->avatar }}"
          style="width:150px; height:150px; border-radius:50%; margin-right:25px;">
        <form action="/uplade" method="POST" enctype="multipart/form-data">
          <label>Update Profile Image</label> <br>
          <input type="file" name="avatar">
          @csrf
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <br>
          <input type="submit" class="pull-right ml-3 btn btn-sm btn-primary">
        </form>

      </p>

      <p>
        <b>{{ __('msg.id')}} :</b>
        <br>
        <input class="input" type="number" value="{{Auth::user()->id}}" readonly>
      </p>


      <p>
        <b>{{ __('msg.name')}} :</b>
        <br>
        <input class="input" type="text" value="{{Auth::user()->name}}" readonly>
      </p>

      <p>
        <b>{{ __('msg.email')}} :</b>
        <br>
        <input class="input" type="text" value="{{Auth::user()->email}}" readonly>
      </p>

      <p>
        <b>{{ __('msg.password')}} :</b>
        <br>
        <input class="input" type="text" value="{{Auth::user()->password}}" readonly>
      </p>

      <p>
        <b>{{ __('msg.phone')}} :</b>
        <br>
        <input class="input" type="number" value="{{Auth::user()->phone}}" readonly>
      </p>

      <p>
        <b>{{ __('msg.country')}} :</b>
        <br>
        <input class="input" type="text" value="{{Auth::user()->country}}" readonly>
      </p>

    </tr>
    @foreach ($useres as $i)

    @endforeach
    <!--<td> {{link_to_route('useres.edit','Edit',$i,['class'=>'btn btn-success edit'])}}</td>-->
    <button class="btn btn-primary" style="width:10%; font-size:16px;" data-toggle="modal"
      data-target="#exampleModalCenter2">
      {{ __('msg.edit')}} <span class="text-dark" style="margin-left:15%;"><i class="fas fa-edit text-light"></i></span>
    </button>
    <button class="btn btn-danger" style="width:10%; font-size:16px;" data-toggle="modal"
      data-target="#exampleModalCenter1">
      {{ __('msg.delete')}} <span class="text-dark" style="margin-left:15%;"><i class="fas fa-trash-alt text-light"></i></span>
    </button>
    <td></td>
    </tr>

  </div>
</div>

@if (session('updateprof'))
@include('sweets2.successful-update-prof')
@endif

<style>
  ::-webkit-file-upload-button {
  border: 1px solid var(--primary-skyblue);
  background: var(--primary-skyblue);
  color: white;
  margin-bottom:10px;
  border-radius: 3px;  
  width:100px;
  height:50px;
}
</style>
@endsection
<!-- Content END -->